/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_spiport_SpiPort */

#ifndef _Included_android_spiport_SpiPort
#define _Included_android_spiport_SpiPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_spiport_SpiPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_android_spiport_SpiPort_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     android_spiport_SpiPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_spiport_SpiPort_close
  (JNIEnv *, jobject);

/*
 * Class:     android_spiport_SpiPort
 * Method:    up_cline
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_spiport_SpiPort_up_1cline
  (JNIEnv *, jobject);

/*
 * Class:     android_spiport_SpiPort
 * Method:    down_cline
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_spiport_SpiPort_down_1cline
  (JNIEnv *, jobject);

/*
 * Class:     android_spiport_SpiPort
 * Method:    write
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_android_spiport_SpiPort_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     android_spiport_SpiPort
 * Method:    read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_spiport_SpiPort_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     android_spiport_SpiPort
 * Method:    read_len
 * Signature: (I[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_spiport_SpiPort_read_1len
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     android_spiport_SpiPort
 * Method:    Size_len
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_spiport_SpiPort_Size_1len
  (JNIEnv *, jobject, jint);

/*
 * Class:     android_spiport_SpiPort
 * Method:    len
 * Signature: ([BLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_android_spiport_SpiPort_len
  (JNIEnv *, jobject, jbyteArray, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
