/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPort
#define _Included_android_serialport_api_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_android_serialport_api_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_serialport_api_SerialPort_close
  (JNIEnv *, jobject);
/*
 * Class:     android_spiport_api_SpiPort
 * Method:    up_cline
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_1spiport_1api_SpiPort_up_1cline
  (JNIEnv *, jobject);

/*
 * Class:     android_spiport_api_SpiPort
 * Method:    down_cline
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_1spiport_1api_SpiPort_down_1cline
  (JNIEnv *, jobject);
/*
 * Class:     android_spiport_api_SpiPort
 * Method:    write
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_android_1spiport_1api_SpiPort_write
  (JNIEnv *, jobject, jbyteArray,jint);

/*
 * Class:     android_spiport_api_SpiPort
 * Method:    read
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_1spiport_1api_SpiPort_read
  (JNIEnv *, jobject, jint);
/*
 * Class:     android_spiport_api_SpiPort
 * Method:    read_len
 * Signature: ([BI)I
 */
JNIEXPORT jbyteArray JNICALL Java_android_1spiport_1api_SpiPort_read_1len
  (JNIEnv *, jobject,  jint,jintArray);
/*
 * Class:     android_spiport_api_SpiPort
 * Method:    Size_len
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_android_1spiport_1api_SpiPort_Size_1len
  (JNIEnv *, jobject, jint);
/*
 * Class:     android_spiport_api_SpiPort
 * Method:    len
 * Signature: ([BLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_android_1spiport_1api_SpiPort_len
  (JNIEnv *, jobject, jbyteArray, jstring, jint);
#ifdef __cplusplus
}
#endif
#endif
